sudo: false
language: node_js
node_js: lts/*
cache:
  bundler: true
  pip: true
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
# cf. https://stackoverflow.com/a/52387639
install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry pip install awscli --upgrade --user
  - travis_retry npm ci
  - travis_retry cypress install
script:
  - npm rum test:coverage
  - npm run start & wait-on http://localhost:8080
  - npm run test:cypress
  - npm run build
after_script:
  # If there are no errors, these dirs won't be created and Travis will complain about it while uploading artifacts.
  - mkdir -p ./cypress/screenshots
after_success:
  - ./s3_deploy.sh
addons:
  artifacts:
    paths:
      - ./cypress/screenshots
    target_paths:
      - /hurricane-model/build-artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
